# Generated by Django 3.2.7 on 2021-09-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210927_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'New film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterField(
            model_name='article',
            name='year_of_release',
            field=models.IntegerField(default=2000),
        ),
    ]
